### ISSUE TITLE
Update has caused issues with simple heels working

### ISSUE THREAD

**Issue by abris26** [Caraxi/SimpleHeels#10]
After the latest update there is now an issue where I can not get my heels to move up or down no matter how high I go. There is another thing with items that do not have an offset they are now floating in the air.  I do not know if this is because of the transfer from /xlheels to simple heels or if it was an unintentional issue with the latest update.

**Comment by DyaNox** [comment]
I am having the same issue, heels is not working at all even if I add new shoes or anything. I'm not sure if it's because of this update or the penumbra update though.

**Comment by Yhozora** [comment]
Same here, simpleheels not working at all since this morning. Have tried to delete my character and start a new File but nothing helps.

**Comment by Lockehart** [comment]
Same issue.  Update completely breaks hover

**Comment by Maxunit** [comment]
Same here, update broke SimpleHeels completely and i am always floating a bit.
