### ISSUE TITLE
Floating to others

### ISSUE THREAD

**Issue by MeikoXIV** [Caraxi/SimpleHeels#12]
Everytime I sit with plugin turned on, everyone  is telling me I begin to float very high. 
I tried to change sitting height just a bit to force my character down but it didn't work. Only disabling the plugin works. Do you have any idea what could be the cause?

**Comment by Caraxi** [comment]
This is due to an incompatibility between the LeonBlade's Heels Plugin and Simple Heels I believe
As Heels Plugin has been decommissioned I recommend suggesting friends move over to Simple Heels
