### ISSUE TITLE
[Feature Request] Apply to certain races

### ISSUE THREAD

**Issue by VivyBehe** [Caraxi/SimpleHeels#17]
Hi, I was wondering if it was possible to add a category option to either per character or per heels, to have it apply to specific races. I like to swap between talls and lalafells and unfortunately, there is some overlap of modded shoes (i.e. Calfskin shoes). While these shoes are modded into heels that require offsetting on my talls, if I were to wear a different modded shoe for lalafell, I also end up floating. 

I'd ideally like the option to set heel offsets for different races so that I can wear the same shoes with different offsets.

Thank you

**Comment by Caraxi** [comment]
As of version `0.8.2.0` you can accomplish this using the groups feature.

Create two groups, use name matching to make them only apply to yourself
Set each group to only apply to the specific race/tribes you want each set to apply to.
