### ISSUE TITLE
Offests not applying during Group Pose

### ISSUE THREAD

**Issue by Lapidearum** [Caraxi/SimpleHeels#18]
After the latest update, the plugin doesn't seem to be working in Group Pose. It functions as expected during normal gameplay, but while /gpose is active, offsets simply aren't applied. The interface is still accessible, but toggling applicable entries on and off does nothing.

**Comment by Caraxi** [comment]
Fixed in 85c4de371674636eeb7977bed50cbf469e9073f3
Will be available for plugin update in 10-20 minutes
