### ISSUE TITLE
[Bug] Sitting offset not working in newest cutscenes

### ISSUE THREAD

**Issue by Oktorose** [Caraxi/SimpleHeels#25]
I use a Penumbra mod (Smol or Tall) and Customize+ to make my character taller. As a result, my character floats a bit when they sit on a chair. This plugin does a great job of fixing that issue! In the recent 6.55 MSQ content though, I noticed the sitting offset wasn't working specifically in cutscenes. I attached a picture showing what I'm talking about.

With the plugin, it looks great outside the cutscene, but in the cutscene the plugin just doesn't seem to be affecting it at all.

Thank you for working on this!

![amisit](https://github.com/Caraxi/SimpleHeels/assets/156968455/091073e3-365d-4baf-ad61-37688c60b420)

**Comment by Caraxi** [comment]
Different cutscene designers use different methods to make the character sit, some of them aren’t super detectable. I’ll have a look into it but cutscenes aren’t really the intended target of the plugin
