### ISSUE TITLE
Offsets in Brio/Ktisis/Anam not working with Simple Heels

### ISSUE THREAD

**Issue by JennyIsLivid** [Caraxi/SimpleHeels#29]
![image](https://github.com/Caraxi/SimpleHeels/assets/160799410/2861aa61-9b85-4c5f-83b3-c1c31b27988c)

Changing the top 3 values that usually change character positioning in gpose does nothing. In Ktisis if you enable gpose it works but it's a very hard to work around solution. Turning off Simple heels makes it work again. As far as I've tested it's extremely easy to replicate.
Is mod on? If yes = offset changes do not work. Instead the character will be stuck in place and even flicker if their movement is not frozen before jumping back to their original spot.

**Comment by JennyIsLivid** [comment]
Additional pictures provided as it may be confusing on just works.
![image](https://github.com/Caraxi/SimpleHeels/assets/160799410/60d6c6cf-85dd-421b-8e2e-d107e99a86ff)

Original positioning in pic above with Simple Heels on. Should I change the value of top middle and top left, the character should move upwards and to the side. but instead
![image](https://github.com/Caraxi/SimpleHeels/assets/160799410/0399685e-8825-42d4-94ac-b8346f143474)


Here is the roughly same value changes after disabling Simple Heels
![image](https://github.com/Caraxi/SimpleHeels/assets/160799410/5ac630f4-d74b-49e2-87a0-e4fe3c04477d)
.

**Comment by Caraxi** [comment]
For me:
- Without locking position the Anamnesis one can't be used
- Without enabling Posing the Ktisis one never works, always returns to default position
- Brio works with or without Simple Heels installed

Uninstalling Simple Heels does not seem to affect this at all and I'm not sure how you are experiencing any difference as it doesn't touch the same values as any of them

I can't find a way to replicate this occurring in a way that having simple heels disabled fixes

**Comment by Caraxi** [comment]
please try again with the latest version (`0.9.0.3`)
Hopefully it won't happen anymore

**Comment by JennyIsLivid** [comment]
> please try again with the latest version (`0.9.0.3`) Hopefully it won't happen anymore

Fixed! Tested with update 0.9.0.4 (was asleep during 0.9.0.3 aha ttyyy xx
