### ISSUE TITLE
dosen‘t work for minion

### ISSUE THREAD

**Issue by Tiamatye** [Caraxi/SimpleHeels#31]
i use Glamourer to make my minion become a nomal（male/female） character，but the Simple Heels dosen‘t work for minion

**Comment by Tiamatye** [comment]
![Q%3(YN6)D8RY}T@NVX~8S G](https://github.com/Caraxi/SimpleHeels/assets/162399991/ebbcecce-7127-45d5-ac39-ee861252c29e)
it works for my character，but dosen't for my minion
The old version is working

**Comment by Tiamatye** [comment]
![Uploading 36.jpg…]()

**Comment by Caraxi** [comment]
I've added an option to apply offsets to minions with e2a6de3bb4ef1df0a0e6f8e7c914c79cb2ecf29e
This won't sync with mare yet (or maybe never who knows) 
will be available in next update
