### ISSUE TITLE
Reaper enshroud breaks offset

### ISSUE THREAD

**Issue by jefffi** [Caraxi/SimpleHeels#4]
Using the skill Enshroud on Reaper removes the offset for the duration, making the camera move and refreshing the actor on synced clients

**Comment by Caraxi** [comment]
This is not going to be easy to fix, if it needs fixing

because enshroud changes the clothes you wear for its duration it is technically correct that it removes the offset, but the camera movement and refreshing is undesirable so I'm not sure how to deal with it

**Comment by Caraxi** [comment]
1ce1263534c6efadd10748230190dca541fded7c
Offsets will no longer be changed while under the effect of Enshroud.
