### ISSUE TITLE
Attributs Not working from TextTools

### ISSUE THREAD

**Issue by Haeresis65** [Caraxi/SimpleHeels#7]
Sorry for the spam. I use textools (develop) to add attributs, when I use "heels_offset=X.XXXX" it's not working, but when I use "heels_offset=X,XXXX", thats works.

I think float.tryparse not work with "."

PS. Negative values not working in Textools

**Comment by Caraxi** [comment]
I can fix the decimal and comma issue, but the textools issue will have to be fixed on their side
