### ISSUE TITLE
[Feature Request] Ground Sit & Sleep Offset

### ISSUE THREAD

**Issue by Azreak** [Caraxi/SimpleHeels#8]
Requesting Groundsit and Sleeping height to have Adjustments added back in, if said feature wasn't already planned.

**Comment by Tsuyara** [comment]
Can only second this, being to adjust sleep height is one of the things i miss most from the old heels.

**Comment by cobelt021** [comment]
Yes please, this is the only reason I used the old heels plugin! Does anyone know of any alternative that allows you to adjust groundsit/sleep height?

**Comment by Caraxi** [comment]
I've added an option for ground sit and sleeping
will be in the next update when that comes
b71c3ecc0705c93b15a26ee9c6740cecc8f71adf
