### ISSUE TITLE
Last update completely broke Simple Heels

### ISSUE THREAD

**Issue by YukihimeNakano** [Caraxi/SimpleHeels#9]
When i use a ''heeled'' shoe, it goes up, but then i don't use a heel (or i go barefoot, casual shoes, etc) it doesn't reset it to 0 automatically, i have to sit on a chair or it keeps me floating. really love your plugin tho ♥ Also sometimes doesn't work from one heel height to another x3, hope it helps.

**Comment by Cerrelle** [comment]
I'm seeing the same issue, even after updating to v0.6.1.2

**Comment by Cerrelle** [comment]
v0.6.1.3 seems to have corrected the issues I was seeing with permanent float height.
